const mongoose = require ('mongoose');

const ProfileSchema = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String,
        trim:true
    },
    website:{
        type:String,
        trim:true
    },
    location:{
        type:String,
        trim:true
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true,
    },
    bio:{
        type:String,
        trim:true
    },
    githubusername:{
        type:String,
        trim:true
    },
    experience:[
        {
            title:{
                type:String,
                trim:true,
                required:true
            },
            company:{
                type:String,
                trim:true,
                required:true
            },
            location:{
                type:String,
                trim:true
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String,
                trim:true
            }
        }

    ],
    education:[
        {
            school:{
                type:String,
                trim:true,
                required:true
            },
            degree:{
                type:String,
                trim:true,
                required:true
            },
            fieldofstudy:{
                type:String,
                trim:true,
                required:true,
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String,
                trim:true
            }
        }
    ],
    social:{
        youtube:{
            type:String,
            trim:true
        },
        twiter:{
            type:String,
            trim:true
        },
        facebook:{
            type:String,
            trim:true
        },
        linkedin:{
            type:String,
            trim:true
        },
        instagram:{
            type:String,
            trim:true
        }
    }
});

module.exports = Profile = mongoose.model('profile',ProfileSchema);